version: '2'

services:

  app:
    build: .
    container_name: ArepTaller6SecureApplicationDesign
    restart: always
    depends_on:
      - mysql
    environment:
      # la IP de la bd de AWS
      SPRING_DATASOURCE_URL: jdbc:mysql://72.44.61.48:3306/properties?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network: